repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=file]
      - id: clang-tidy
        args: [--format-style=file]
  - repo: https://gitlab.com/liferooter/hse-cpp-hooks
    rev: v1.1.0
    hooks:
      - id: no-extra-files
      - id: test-task
